// <auto-generated />
using System;
using ArrowThing.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArrowThing.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401000001_AddLoginLockout")]
    partial class AddLoginLockout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ArrowThing.Server.Models.User",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime?>("EmailVerifiedAt").HasColumnType(
                        "timestamp with time zone"
                    );

                    b.Property<int>("FailedLoginAttempts").HasColumnType("integer");

                    b.Property<DateTime?>("LastPasswordResetEmailAt").HasColumnType(
                        "timestamp with time zone"
                    );

                    b.Property<DateTime?>("LastVerificationEmailAt").HasColumnType(
                        "timestamp with time zone"
                    );

                    b.Property<DateTime?>("LockedAt").HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd").HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");

                    b.Property<string>("PasswordResetCode").HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetCodeExpiresAt").HasColumnType(
                        "timestamp with time zone"
                    );

                    b.Property<string>("PendingEmail").HasColumnType("text");

                    b.Property<string>("PendingEmailCode").HasColumnType("text");

                    b.Property<DateTime?>("PendingEmailCodeExpiresAt").HasColumnType(
                        "timestamp with time zone"
                    );

                    b.Property<string>("SecurityStamp").IsRequired().HasColumnType("text");

                    b.Property<string>("VerificationCode").HasColumnType("text");

                    b.Property<DateTime?>("VerificationCodeExpiresAt").HasColumnType(
                        "timestamp with time zone"
                    );

                    b.HasKey("Id");

                    b.HasIndex("Email").IsUnique();

                    b.ToTable("Users");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
